version: '3.8'
services:
app:
image: shrikantdayma/swarm-app:${TAG}
ports:
- "8081:3000"
volumes:
- visits_data:/app/data
deploy:
replicas: 2
restart_policy:
condition: on-failure
volumes:
visits_data:
driver: local
